# Generated by Django 6.0.3 on 2026-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter',
        ),
        migrations.AddField(
            model_name='user',
            name='social_link',
            field=models.URLField(blank=True),
        ),
    ]
