# Generated by Django 6.0.3 on 2026-04-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_instagram_remove_user_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pref_age_max',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pref_age_min',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pref_gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
